version: "3"
services:
  rmi-server:
    image: wimmelsoft/rmi-server:1.0.0
    hostname: rmi-server
    networks:
      - demo

  rmi-client:
    image: wimmelsoft/rmi-client:1.0.0
    hostname: rmi-client
    ports:
      - "80:8081"
    environment:
      RMI_OPTS: "-DRMI_SERVER_HOST=rmi-server"
    networks:
      - demo

networks:
  demo:
    driver: overlay