version: "3"
services:
  rmi-server:
    image: wimmelsoft/rmi-demo:1.0.1
    hostname: rmi-server
    ports:
      - "80:8089"
    environment:
      JAVA_OPTS: "-DRMI_HOST=localhost"
    networks:
      - demo

  rmi-client:
    image: wimmelsoft/rmi-demo:1.0.1
    hostname: rmi-client
    ports:
      - "81:8089"
    environment:
      JAVA_OPTS: "-DRMI_HOST=rmi-server"
    networks:
      - demo

networks:
  demo:
    driver: overlay